### ISSUE TITLE
Project Report

### ISSUE THREAD

**Issue by srowhani** [proccoli/proccoli-pm#20]
# DUE DATES:
Demo: Dec 7th or Dec 9th
Report: Dec 9th

https://drive.google.com/drive/folders/0B6ps-QjUme6vckQ1Zl9LOENNNm8
## Part 0 - Getting Started
- [x] `Title Page`
    - [x] Title
    - [x] Author Names, lexicographically by last name 

## Part 1 - Introduction (Seena)
- [x] `Context`
    - [x] General background info
- [x] `Problem Statement`
    - [x] Problems we are addressing
    - [x] Project goals
    - [x] Project achievables
    - [x] Project Motivations
- [x] `Result`
    - In reference to problems and goals outlined in the `Problem Statement`, 
      - [x] Describe what has been done
      - [x] Highlights of working on this project. 
      - [x] How have you achieved your goals
- [x] `Outline` (Shane)
    - [x] Describe format of the document

## Part 2 - Background Information (Seena)
- [x] In your OWN WORDS, review in detail the concepts and previous works (things on which you are building upon) related to you project.
      - Repeating myself

## Part 3 - Result (Shane)
- [x] Describe work that has been achieved
        - Design Patterns
- [x] Review interface, with representative use cases.
- [x] Describe code 
    - Code snippets
- [x] UML describing architecture (Seena)
- [x] Screenshots (Seena)

## Part 4 - Evaluation (Seena / Shane)
Be honest, self critical and objective about your work. If you make claims related to performance, such as fast or small, provide an analytic model (e.g., complexity analysis) or statistical data to support your claims. Try your software under typical scenarios. Collect data, e.g., execution, connection, round trip time or transfer time, delay, latency, throughput, memory or bandwidth usage, error or success rate. Plot and analyze the data. If you make claims such as faster or smaller, then explain with respect to what and why. Provide comparative analyses or statistical data. If you make claims such as easy to use, conduct a usability study involving people from the community of potential users of you software (see Ref. [3]). Prepare evaluation scenarios and evaluation questions. Collect comments. Analyze them. Ideally, the users who participate in your study should be independent and critical. You may involve class mates, friends or family members in your study. If you make claims such as easier to use, then explain with respect to what and why. Conduct a comparative usability study.

If your project is security related (e.g., attack method, detection or mitigation), then use evaluation metrics such as success rate, false positive alarms or false negative alarms. Data is always easier to grasp when presented graphically, rather than in a cryptic numerical tabular form. Use plots, scatter plots, bar charts, pie charts, box plots, etc. You may use colors, but plots, charts and diagrams must also be readable in when printed black and white, without any loss of information.

## Part 5 - Conclusion (Shane)
- [x] Summary
    - summarize work, highlight achievements
- [x] Relevance
    - How it's relevant to the course topics.
- [x] Future Work

## Part 6 - Contribution Breakdown (Seena / Shane)
- [x] Write up explaining who did what.

**Comment by SSlatter** [comment]
[Proccoli-SummaryDisplay.pdf](https://github.com/proccoli/proccoli-pm/files/623428/Proccoli-SummaryDisplay.pdf)
My UML part. I can't add .xml files so take a look and let me know if if you want me too add anything else as its pretty basic. Ill send you the .xml file if you need it over discord. cheers

**Comment by srowhani** [comment]
I uploaded a uml to our drive folder. Cheers

**Comment by SSlatter** [comment]
awks

**Comment by srowhani** [comment]
Feel free to modify if you want to use an intermediate CPUListWalker class between the CPUList and the Meters.

**Comment by srowhani** [comment]
LMAOOOOOO yo what up

**Comment by SSlatter** [comment]
Hi
